name: CD
on: push

jobs:
  snap:
    name: Push to snap
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: Install review tools
        run: sudo snap install review-tools

      - name: Build snap
        run: sg lxd -c 'snapcraft --use-lxd'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: taskwarrior-tui
          path: taskwarrior-tui_*.snap
